def sum_(a, b):
    print(f'A = {a} e B = {b}')
    print('The sum of A + B =', a + b)


sum_(4, 5)
sum_(a=8, b=9)
sum_(b=8, a=9)
# sum_(b=2, 1) ERROR
